[workspace]
members = ["stecs-derive"]

[workspace.package]
version = "0.1.2"
edition = "2021"

[package]
name = "stecs"
version.workspace = true
edition.workspace = true
license = "MIT"
authors = ["Nertsal <nestralnertsal@gmail.com>"]
description = "Experimental static compiler-checked ECS library"
documentation = "https://docs.rs/stecs"
readme = "README.md"
homepage = "https://github.com/Nertsal/stecs"
repository = "https://github.com/Nertsal/stecs"

[features]
default = ["arena", "query_mut"]
query_mut = ["stecs-derive/query_mut"]
hashstorage = []
arena = ["dep:slotmap"]

[dependencies]
stecs-derive = { path = "stecs-derive", version = "0.1.0" }
slotmap = { version = "1.0", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[package.metadata."docs.rs"]
all-features = true

[[bench]]
name = "pos_vel"
harness = false
required-features = ["query_mut"]
[[bench]]
name = "simple"
harness = false
required-features = ["query_mut"]

[[example]]
name = "full"
doc-scrape-examples = true
required-features = ["query_mut"]

[[example]]
name = "blogpost"
doc-scrape-examples = true
required-features = ["arena", "query_mut"]

[[example]]
name = "mutations"
doc-scrape-examples = true
required-features = ["query_mut"]

[[example]]
name = "generics"
doc-scrape-examples = true
required-features = []
