[workspace]
members = ["stecs-derive"]

[workspace.package]
version = "0.1.2"
edition = "2021"

[package]
name = "stecs"
version.workspace = true
edition.workspace = true
license = "MIT"
authors = ["Nertsal <nestralnertsal@gmail.com>"]
description = "Experimental static compiler-checked ECS library"
documentation = "https://docs.rs/stecs"
readme = "README.md"
homepage = "https://github.com/Nertsal/stecs"
repository = "https://github.com/Nertsal/stecs"

[features]
default = ["slotmap", "query_mut"]
query_mut = ["stecs-derive/query_mut"]
slotmap = ["dep:slotmap"]
zero_vec = []

[dependencies]
stecs-derive = { path = "stecs-derive", version = "0.1.0" }
slotmap = { version = "1.0", optional = true }

[dev-dependencies]
criterion = { version = "0.6", default-features = false, features = ["cargo_bench_support", "plotters", "html_reports"] }
rayon = "1.10.0"
bevy_ecs = "0.15.3"
hecs = "0.10.5"
legion = "0.4.0"
gecs = "0.3.0"

[package.metadata."docs.rs"]
all-features = true

[[bench]]
name = "benchmarks"
harness = false
required-features = ["slotmap", "zero_vec", "query_mut"]

[[example]]
name = "full"
doc-scrape-examples = true
required-features = ["slotmap", "query_mut"]

[[example]]
name = "blogpost"
doc-scrape-examples = true
required-features = ["slotmap", "query_mut"]

[[example]]
name = "mutations"
doc-scrape-examples = true
required-features = ["slotmap", "query_mut"]

[[example]]
name = "generics"
doc-scrape-examples = true
required-features = ["slotmap"]
