use super::*;

impl Struct {
    pub(super) fn generate_struct_archetype(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
        struct_of_name: &syn::Ident,
        struct_ref_name: &syn::Ident,
        struct_ref_mut_name: &syn::Ident,
    ) -> TokenStream {
        let struct_of = self.generate_struct_of(
            generic_usage,
            generic_family_name,
            struct_split_name,
            struct_of_name,
        );
        let struct_of_clone = self.generate_struct_of_clone(
            generic_usage,
            generic_family_name,
            struct_split_name,
            struct_of_name,
        );
        let struct_of_impl = self.generate_struct_of_impl(
            generic_usage,
            generic_family_name,
            struct_of_name,
            struct_ref_name,
            struct_ref_mut_name,
        );
        let struct_of_archetype = self.generate_struct_of_archetype(
            generic_usage,
            generic_family_name,
            struct_split_name,
            struct_of_name,
        );

        let struct_of_default =
            self.generate_struct_of_default(generic_usage, generic_family_name, struct_of_name);

        quote! {
            #struct_of
            #struct_of_clone
            #struct_of_impl
            #struct_of_archetype
            #struct_of_default
        }
    }

    fn generate_struct_of(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
        struct_of_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let vis = &self.visibility;
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use: _,
            generics_family_use,
        } = generic_usage;

        let struct_of_doc = format!(
            r#"Generated by `#[derive(SplitFields)]`.
This struct is a version of `{struct_name}` that holds each field in its own [Storage]({crate_name}::storage::Storage).

**Note**: It is not intended to be used directly, but rather as, for example, `StructOf<Vec<{struct_name}>>`."#
        );

        quote! {
            #[doc = #struct_of_doc]
            #vis struct #struct_of_name<#generics_family> {
                /// The id's of all existing entities belonging to this archetype.
                ///
                /// **Note**: not intended to be used directly,
                /// but rather via methods and querying macros.
                /// *It is only exposed to be accessible in queries*.
                pub ids: #generic_family_name::IdGenerator,
                /// The inner fields of the archetype.
                ///
                /// **Note**: not intended to be used directly,
                /// but rather via methods and querying macros.
                /// *It is only exposed to be accessible in queries*.
                pub inner: #struct_split_name<#generics_family_use>,
            }
        }
    }

    fn generate_struct_of_clone(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
        struct_of_name: &syn::Ident,
    ) -> TokenStream {
        let generics_family = &generic_usage.generics_family;
        let generics_family_use = &generic_usage.generics_family_use;

        quote! {
            impl<#generics_family> ::std::clone::Clone for #struct_of_name<#generics_family_use>
            where
                #generic_family_name::IdGenerator: ::std::clone::Clone,
                #struct_split_name<#generics_family_use>: ::std::clone::Clone,
            {
                fn clone(&self) -> Self {
                    Self {
                        ids: self.ids.clone(),
                        inner: self.inner.clone(),
                    }
                }
            }
        }
    }

    fn generate_struct_of_impl(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_of_name: &syn::Ident,
        struct_ref_name: &syn::Ident,
        struct_ref_mut_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use,
            generics_family_use,
        } = generic_usage;

        let fields = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { #name, }
            })
            .collect::<Vec<_>>();

        let mut get = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { let #name = self.#name.get(id)?; }
            })
            .collect::<Vec<_>>();
        get.push(quote! {
            Some(#struct_ref_name {
                #(#fields)*
            })
        });

        let mut get_mut = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { let #name = self.#name.get_mut(id)?; }
            })
            .collect::<Vec<_>>();
        get_mut.push(quote! {
            Some(#struct_ref_mut_name {
                #(#fields)*
            })
        });

        let get_doc = format!(
            r#"Get an immutable reference to all components of this archetype, i.e. a [`{struct_ref_name}`]"#
        );
        let get_mut_doc = format!(
            r#"Get an mutable reference to all components of this archetype, i.e. a [`{struct_ref_mut_name}`]"#
        );

        let insert_doc =
            format!(r#"Insert a new entity of type [`{struct_name}`], returning its id."#);

        let iter_doc = format!(
            r#"Iterate over all components of this archetype, i.e. over [`{struct_ref_name}`]"#
        );

        #[cfg(not(feature = "query_mut"))]
        let query_mut = quote! {};
        #[cfg(feature = "query_mut")]
        let query_mut = {
            let iter_mut_doc = format!(
                r#"Iterate mutably over all components of this archetype, i.e. over [`{struct_ref_mut_name}`]"#
            );

            quote! {
                #[doc = #iter_mut_doc]
                pub fn iter_mut(&mut self) -> impl Iterator<Item = (#generic_family_name::Id, #struct_ref_mut_name<'_, #generics_use>)> {
                    use #crate_name::storage::IdGenerator;
                    self.ids.ids().filter_map(|id| {
                        let item = self.inner.get_mut(id)?;
                        let item = unsafe { #crate_name::UpcastLifetime::upcast(item) };
                        Some((id, item))
                    })
                }
            }
        };

        quote! {
            impl<#generics_family> #struct_of_name<#generics_family_use> {
                pub fn new() -> Self
                where
                    #struct_of_name<#generics_family_use>: ::std::default::Default
                {
                    Self::default()
                }

                #[doc = #insert_doc]
                pub fn insert(&mut self, value: #struct_name<#generics_use>) -> #generic_family_name::Id {
                    use #crate_name::{archetype::Split, storage::IdGenerator};
                    let id = self.ids.spawn();
                    self.inner.insert(id, value);
                    id
                }

                #[doc = #get_doc]
                pub fn get(&self, id: #generic_family_name::Id) -> Option<#struct_ref_name<'_, #generics_use>> {
                    self.inner.get(id)
                }

                #[doc = #get_mut_doc]
                pub fn get_mut(&mut self, id: #generic_family_name::Id) -> Option<#struct_ref_mut_name<'_, #generics_use>> {
                    self.inner.get_mut(id)
                }

                #[doc = #iter_doc]
                pub fn iter(&self) -> impl Iterator<Item = (#generic_family_name::Id, #struct_ref_name<'_, #generics_use>)> {
                    use #crate_name::storage::IdGenerator;
                    self.ids.ids().filter_map(|id| self.inner.get(id).map(move |item| (id, item)))
                }

                #query_mut
            }

            impl<#generics_family> IntoIterator for #struct_of_name<#generics_family_use> {
                type Item = (#generic_family_name::Id, #struct_name<#generics_use>);
                type IntoIter = #crate_name::archetype::ArchetypeIntoIter<#generic_family_name, #struct_of_name<#generics_family_use>>;

                fn into_iter(self) -> Self::IntoIter {
                    #crate_name::archetype::ArchetypeIntoIter::new(self)
                }
            }
        }
    }

    fn generate_struct_of_archetype(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
        struct_of_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use,
            generics_family_use,
        } = generic_usage;

        quote! {
            impl<#generics_family> #crate_name::archetype::Archetype<#generic_family_name> for #struct_of_name<#generics_family_use> {
                type Item = #struct_name<#generics_use>;
                type Split = #struct_split_name<#generics_family_use>;
                fn ids(&self) -> impl Iterator<Item = #generic_family_name::Id> {
                    use #crate_name::storage::IdGenerator;
                    self.ids.ids()
                }
                fn remove(&mut self, id: #generic_family_name::Id) -> Option<Self::Item> {
                    use #crate_name::{archetype::Split, storage::IdGenerator};
                    if !self.ids.remove(id) {
                        return None;
                    }
                    self.inner.remove(id)
                }
            }
        }
    }

    fn generate_struct_of_default(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_of_name: &syn::Ident,
    ) -> TokenStream {
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use: _,
            generics_family_use,
        } = generic_usage;

        quote! {
            impl<#generics_family> ::std::default::Default for #struct_of_name<#generics_family_use>
            where
                #generic_family_name::IdGenerator: ::std::default::Default
            {
                fn default() -> Self {
                    Self {
                        ids: ::std::default::Default::default(),
                        inner: ::std::default::Default::default(),
                    }
                }
            }
        }
    }
}
