use super::*;

impl Struct {
    pub(super) fn generate_struct_archetype(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        lifetime_ref_name: &TokenStream,
        struct_of_name: &syn::Ident,
        struct_ref_name: &syn::Ident,
        struct_ref_mut_name: &syn::Ident,
    ) -> TokenStream {
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use: _,
            generics_family_use,
        } = generic_usage;

        let struct_of = self.generate_struct_of(generic_usage, generic_family_name, struct_of_name);
        let struct_of_clone =
            self.generate_struct_of_clone(generic_usage, generic_family_name, struct_of_name);
        let struct_of_impl = self.generate_struct_of_impl(
            generic_usage,
            generic_family_name,
            lifetime_ref_name,
            struct_of_name,
            struct_ref_name,
            struct_ref_mut_name,
        );
        let struct_of_archetype =
            self.generate_struct_of_archetype(generic_usage, generic_family_name, struct_of_name);

        let struct_of_default = {
            let fields = self
                .fields
                .iter()
                .map(|field| {
                    let name = &field.name;
                    quote! {
                        #name: Default::default()
                    }
                })
                .collect::<Vec<_>>();

            quote! {
                impl<#generics_family> Default for #struct_of_name<#generics_family_use> {
                    fn default() -> Self {
                        Self {
                            ids: Default::default(),
                            #(#fields),*
                        }
                    }
                }
            }
        };

        quote! {
            #struct_of
            #struct_of_clone
            #struct_of_impl
            #struct_of_archetype
            #struct_of_default
        }
    }

    fn generate_struct_of(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_of_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let vis = &self.visibility;
        let generics_family = &generic_usage.generics_family;

        let mut fields = self.fields
                .iter()
                .map(|field| {
                    let name = &field.name;
                    let ty = &field.ty;
                    let ty = if field.nested {
                        quote! { <#ty as #crate_name::archetype::SplitFields<#generic_family_name>>::StructOf }
                    } else {
                        quote! { #generic_family_name::Storage<#ty> }
                    };
                    quote! {
                        pub #name: #ty,
                    }
                })
                .collect::<Vec<_>>();
        fields.push(quote! { pub ids: #generic_family_name::Storage<()>, });

        let struct_of_doc = format!(
            r#"Generated by `#[derive(SplitFields)]`.
This struct is a version of `{struct_name}` that holds each field in its own [Storage]({crate_name}::storage::Storage).

**Note**: It is not intended to be used directly, but rather as, for example, `StructOf<Vec<{struct_name}>>`."#
        );

        quote! {
            #[doc = #struct_of_doc]
            #vis struct #struct_of_name<#generics_family> {
                #(#fields)*
            }
        }
    }

    fn generate_struct_of_clone(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_of_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let generics_family = &generic_usage.generics_family;
        let generics_family_use = &generic_usage.generics_family_use;

        let mut constraints = self.fields
                .iter()
                .map(|field| {
                    let ty = &field.ty;
                    if field.nested {
                        quote! { <#ty as #crate_name::archetype::SplitFields<#generic_family_name>>::StructOf: Clone }
                    } else {
                        quote! { #generic_family_name::Storage<#ty>: Clone }
                    }
                })
                .collect::<Vec<_>>();
        constraints.push(quote! { #generic_family_name::Storage<()>: Clone });

        let mut clone = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { #name: self.#name.clone(), }
            })
            .collect::<Vec<_>>();
        clone.push(quote! { ids: self.ids.clone(), });

        quote! {
                impl<#generics_family> Clone for #struct_of_name<#generics_family_use>
                where
                    #(#constraints),*
                {
                    fn clone(&self) -> Self {
                        Self {
                            #(#clone)*
                        }
                    }
                }
        }
    }

    fn generate_struct_of_impl(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        lifetime_ref_name: &TokenStream,
        struct_of_name: &syn::Ident,
        struct_ref_name: &syn::Ident,
        struct_ref_mut_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use,
            generics_family_use,
        } = generic_usage;

        let fields = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { #name, }
            })
            .collect::<Vec<_>>();

        let mut get = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { let #name = self.#name.get(id)?; }
            })
            .collect::<Vec<_>>();
        get.push(quote! {
            Some(#struct_ref_name {
                #(#fields)*
            })
        });

        let mut get_mut = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { let #name = self.#name.get_mut(id)?; }
            })
            .collect::<Vec<_>>();
        get_mut.push(quote! {
            Some(#struct_ref_mut_name {
                #(#fields)*
            })
        });

        let get_doc = format!(
            r#"Get an immutable reference to all components of this archetype, i.e. a [`{struct_ref_name}`]"#
        );
        let get_mut_doc = format!(
            r#"Get an mutable reference to all components of this archetype, i.e. a [`{struct_ref_mut_name}`]"#
        );
        let iter_doc = format!(
            r#"Iterate immutably over all components of this archetype, i.e. over [`{struct_ref_name}`]"#
        );

        #[cfg(not(feature = "query_mut"))]
        let query_mut = quote! {};
        #[cfg(feature = "query_mut")]
        let query_mut = {
            let mut iter_mut = Vec::new();
            let mut get_many_mut = Vec::new();
            if fields.is_empty() {
                // No fields
                iter_mut.push(quote! { ::std::iter::empty() });
                get_many_mut.push(quote! { ::std::iter::empty() });
            } else {
                // Collect fields
                iter_mut = self.fields
                    .iter()
                    .map(|field| {
                        let name = &field.name;
                        quote! {
                            let #name = unsafe { self.#name.get_many_unchecked_mut(self.ids.ids()) };
                        }
                    })
                    .collect();

                // Zip fields
                let zip = std::iter::once(quote! { self.ids.ids() }).chain(self.fields.iter().map(
                    |field| {
                        let name = &field.name;
                        quote! { .zip(#name) }
                    },
                ));
                iter_mut.extend(zip);

                // Construct the arguments for the lambda function
                let mut args = quote! { id };
                for field in self.fields.iter().map(|field| &field.name) {
                    args = quote! { (#args, #field) };
                }

                // Construct the lambda function
                iter_mut.push(quote! {
                    .filter_map(|#args| {
                        Some((
                            id,
                            #struct_ref_mut_name {
                                #(#fields)*
                            }
                        ))
                    })
                });

                // Get many mut

                let ids_expr = quote! { __ids };

                // Collect fields
                let get_fields = self.fields.iter().map(|field| {
                    let name = &field.name;
                    quote! {
                        let #name = unsafe { self.#name.get_many_unchecked_mut(#ids_expr.clone()) };
                    }
                });
                get_many_mut.extend(get_fields);

                // Zip fields
                let mut zip = self.fields.iter().map(|field| &field.name);
                if let Some(name) = zip.next() {
                    get_many_mut.push(quote! { #name });
                }
                for name in zip {
                    get_many_mut.push(quote! { .zip(#name) });
                }

                // Construct the arguments for the lambda function
                let mut args = quote! {};
                let mut args_iter = self.fields.iter().map(|field| &field.name);
                if let Some(field) = args_iter.next() {
                    args = quote! { #field }
                }
                for field in args_iter {
                    args = quote! { (#args, #field) };
                }

                // Construct the lambda function
                get_many_mut.push(quote! {
                    .map(|#args| {
                        #struct_ref_mut_name {
                            #(#fields)*
                        }
                    })
                });
            }

            let iter_mut_doc = format!(
                r#"Iterate mutably over all components of this archetype, i.e. over [`{struct_ref_mut_name}`]"#
            );

            let get_many_unchecked_mut_doc = format!(
                r#"**NOTE**: This function is used internally by the proc macros, you should not call it manually.

Get mutable references to all id's in the iterator, returning an iterator of [`{struct_ref_mut_name}`].

# Safety
The given `ids` must not repeat and must be valid and present id's in the storage."#
            );

            quote! {
                #[doc = #iter_mut_doc]
                pub fn iter_mut<#lifetime_ref_name>(&#lifetime_ref_name mut self) -> impl Iterator<Item = (#generic_family_name::Id, #struct_ref_mut_name<#lifetime_ref_name, #generics_use>)> + #lifetime_ref_name {
                    use #crate_name::archetype::Archetype;
                    #(#iter_mut)*
                }

                #[doc = #get_many_unchecked_mut_doc]
                pub unsafe fn get_many_unchecked_mut<#lifetime_ref_name>(
                    &#lifetime_ref_name mut self,
                    __ids: impl Iterator<Item = #generic_family_name::Id> + Clone,
                ) -> impl Iterator<Item = #struct_ref_mut_name<#lifetime_ref_name, #generics_use>> {
                    #(#get_many_mut)*
                }
            }
        };

        quote! {
            impl<#generics_family> #struct_of_name<#generics_family_use> {
                pub fn new(&self) -> Self {
                    Self::default()
                }

                pub fn phantom_data(&self) -> ::std::marker::PhantomData<#generic_family_name> {
                    ::std::default::Default::default()
                }

                #[doc = #get_doc]
                pub fn get(&self, id: #generic_family_name::Id) -> Option<#struct_ref_name<'_, #generics_use>> {
                    use #crate_name::storage::Storage;
                    #(#get)*
                }

                #[doc = #get_mut_doc]
                pub fn get_mut(&mut self, id: #generic_family_name::Id) -> Option<#struct_ref_mut_name<'_, #generics_use>> {
                    use #crate_name::storage::Storage;
                    #(#get_mut)*
                }

                #[doc = #iter_doc]
                pub fn iter(&self) -> impl Iterator<Item = (#generic_family_name::Id, #struct_ref_name<'_, #generics_use>)> {
                    use #crate_name::archetype::Archetype;
                    self.ids().filter_map(|id| self.get(id).map(move |item| (id, item)))
                }

                #query_mut
            }

            impl<#generics_family> IntoIterator for #struct_of_name<#generics_family_use> {
                type Item = (#generic_family_name::Id, #struct_name<#generics_use>);
                type IntoIter = #crate_name::archetype::ArchetypeIntoIter<#generic_family_name, #struct_of_name<#generics_family_use>>;

                fn into_iter(self) -> Self::IntoIter {
                    #crate_name::archetype::ArchetypeIntoIter::new(self)
                }
            }
        }
    }

    fn generate_struct_of_archetype(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_of_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use,
            generics_family_use,
        } = generic_usage;

        let mut insert = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! {
                    self.#name.insert(value.#name);
                }
            })
            .collect::<Vec<_>>();
        insert.push(quote! { let id = self.ids.insert(()); });
        insert.push(quote! { id });

        let mut remove = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! {
                    let #name = self.#name.remove(id)?;
                }
            })
            .collect::<Vec<_>>();
        remove.push(quote! { self.ids.remove(id)?; });
        let fields = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! {#name}
            })
            .collect::<Vec<_>>();
        remove.push(quote! { Some( #struct_name { #(#fields),* } )});

        quote! {
            impl<#generics_family> #crate_name::archetype::Archetype<#generic_family_name> for #struct_of_name<#generics_family_use> {
                type Item = #struct_name<#generics_use>;
                fn ids(&self) -> impl Iterator<Item = #generic_family_name::Id> {
                    use #crate_name::storage::Storage;
                    self.ids.ids()
                }
                fn insert(&mut self, value: Self::Item) -> #generic_family_name::Id {
                    use #crate_name::storage::Storage;
                    #(#insert)*
                }
                fn remove(&mut self, id: #generic_family_name::Id) -> Option<Self::Item> {
                    use #crate_name::storage::Storage;
                    #(#remove)*
                }
            }
        }
    }
}
