use super::*;

impl Struct {
    pub(super) fn generate_struct_references(
        &self,
        generic_usage: &GenericUsage,
        lifetime_ref_name: &TokenStream,
        struct_ref_name: &syn::Ident,
        struct_ref_mut_name: &syn::Ident,
    ) -> TokenStream {
        let struct_ref_to_owned = self.generate_struct_ref_to_owned(generic_usage);

        let struct_ref = self.generate_struct_ref(
            generic_usage,
            lifetime_ref_name,
            struct_ref_name,
            &struct_ref_to_owned,
        );
        let struct_ref_mut = self.generate_struct_ref_mut(
            generic_usage,
            lifetime_ref_name,
            struct_ref_mut_name,
            &struct_ref_to_owned,
        );
        let struct_ref_impl = self.generate_struct_ref_impl(
            generic_usage,
            lifetime_ref_name,
            struct_ref_name,
            struct_ref_mut_name,
        );

        quote! {
            #struct_ref
            #struct_ref_mut
            #struct_ref_impl
        }
    }

    fn generate_struct_ref_to_owned(&self, generic_usage: &GenericUsage) -> TokenStream {
        let struct_name = &self.name;
        let generics_use = &generic_usage.generics_use;

        let to_owned_constraints = self
            .generics
            .params
            .iter()
            .map(|generic| match generic {
                syn::GenericParam::Lifetime(_) => quote! {},
                syn::GenericParam::Type(param) => {
                    let name = &param.ident;
                    quote! { #name: ::std::clone::Clone, }
                }
                syn::GenericParam::Const(_) => quote! {},
            })
            .collect::<Vec<_>>();

        let fields = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { #name: self.#name.clone(), }
            })
            .collect::<Vec<_>>();

        quote! {
            pub fn clone(&self) -> #struct_name<#generics_use>
            where #(#to_owned_constraints)*
            {
                #struct_name {
                    #(#fields)*
                }
            }
        }
    }

    fn generate_struct_ref_impl(
        &self,
        generic_usage: &GenericUsage,
        lifetime_ref_name: &TokenStream,
        struct_ref_name: &syn::Ident,
        struct_ref_mut_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let lifename = quote! { #lifetime_ref_name };
        let generics = &generic_usage.generics;
        let generics_use = &generic_usage.generics_use;

        let impl_generics: Vec<_> = self
            .generics
            .params
            .iter()
            .map(|param| match param {
                syn::GenericParam::Type(param) => {
                    let ident = &param.ident;
                    quote! { #ident }
                }
                syn::GenericParam::Lifetime(_) => lifename.clone(),
                syn::GenericParam::Const(param) => {
                    let ident = &param.ident;
                    quote! { #ident }
                }
            })
            .collect();
        let impl_generics = quote! { #(#impl_generics),* };

        quote! {
            impl<#generics> #crate_name::archetype::StructRef for #struct_name<#generics_use> {
                type Ref<#lifename> = #struct_ref_name<#lifename, #impl_generics>;
                type RefMut<#lifename> = #struct_ref_mut_name<#lifename, #impl_generics>;
            }
        }
    }

    fn generate_struct_ref(
        &self,
        generic_usage: &GenericUsage,
        lifetime_ref_name: &TokenStream,
        struct_ref_name: &syn::Ident,
        struct_ref_to_owned: &TokenStream,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let vis = &self.visibility;
        let generics = &generic_usage.generics;
        let generics_use = &generic_usage.generics_use;

        let fields = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                let ty = &field.ty;
                let ty = if field.nested {
                    quote! { <#ty as #crate_name::archetype::StructRef>::Ref<#lifetime_ref_name> }
                } else {
                    quote! { &#lifetime_ref_name #ty }
                };
                quote! { pub #name: #ty, }
            })
            .collect::<Vec<_>>();

        let derive = if self.derive_debug {
            quote! { #[derive(Debug)] }
        } else {
            quote! {}
        };

        let struct_ref_doc = format!(
            r#"Generated by `#[derive(SplitFields)]`.
This struct is a version of [`{struct_name}`] that holds references to its fields."#
        );

        let struct_ref = quote! {
            #[doc = #struct_ref_doc]
            #vis struct #struct_ref_name<#lifetime_ref_name, #generics_use> {
                #(#fields)*
            }
        };
        let to_owned = if self.derive_to_owned {
            quote! {
                impl<#generics> #struct_ref_name<'_, #generics_use> {
                    #struct_ref_to_owned
                }
            }
        } else {
            quote! {}
        };

        let upcast = self.generate_upcast(generic_usage, struct_ref_name);

        quote! {
            #derive
            #struct_ref
            #to_owned
            #upcast
        }
    }

    fn generate_struct_ref_mut(
        &self,
        generic_usage: &GenericUsage,
        lifetime_ref_name: &TokenStream,
        struct_ref_mut_name: &syn::Ident,
        struct_ref_to_owned: &TokenStream,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let vis = &self.visibility;
        let generics = &generic_usage.generics;
        let generics_use = &generic_usage.generics_use;

        let fields = self.fields
                .iter()
                .map(|field| {
                    let name = &field.name;
                    let ty = &field.ty;
                    let ty = if field.nested {
                        quote! { <#ty as #crate_name::archetype::StructRef>::RefMut<#lifetime_ref_name> }
                    } else {
                        quote! { &#lifetime_ref_name mut #ty }
                    };
                    quote! { pub #name: #ty, }
                })
                .collect::<Vec<_>>();

        let derive = if self.derive_debug {
            quote! { #[derive(Debug)] }
        } else {
            quote! {}
        };

        let struct_ref_mut_doc = format!(
            r#"Generated by `#[derive(SplitFields)]`.
This struct is a version of [`{struct_name}`] that holds mutable references to its fields."#
        );

        let struct_ref = quote! {
            #[doc = #struct_ref_mut_doc]
            #vis struct #struct_ref_mut_name<#lifetime_ref_name, #generics_use> {
                #(#fields)*
            }
        };
        let to_owned = if self.derive_to_owned {
            quote! {
                impl<#generics> #struct_ref_mut_name<'_, #generics_use> {
                    #struct_ref_to_owned
                }
            }
        } else {
            quote! {}
        };

        let upcast = self.generate_upcast(generic_usage, struct_ref_mut_name);

        quote! {
            #derive
            #struct_ref
            #to_owned
            #upcast
        }
    }

    fn generate_upcast(
        &self,
        generic_usage: &GenericUsage,
        struct_ref_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let GenericUsage {
            generics,
            generics_family: _,
            generics_use,
            generics_family_use: _,
        } = generic_usage;

        let constraints = {
            self.generics.params.iter().map(|param| match param {
                syn::GenericParam::Lifetime(param) => {
                    let param = &param.lifetime;
                    quote! { #param: '__target, }
                }
                syn::GenericParam::Type(param) => {
                    let param = &param.ident;
                    quote! { #param: '__target, }
                }
                syn::GenericParam::Const(_) => quote! {},
            })
        };

        quote! {
            impl<'__target, #generics> #crate_name::UpcastLifetime<'__target>
            for #struct_ref_name<'_, #generics_use>
            where #(#constraints)*
            {
                type Target = #struct_ref_name<'__target, #generics_use>;
                unsafe fn upcast(self) -> Self::Target {
                    std::mem::transmute(self)
                }
            }
        }
    }
}
