use super::*;

impl Struct {
    pub(super) fn generate_struct_split(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
        struct_ref_name: &syn::Ident,
        struct_ref_mut_name: &syn::Ident,
    ) -> TokenStream {
        let split = self.generate_split(generic_usage, generic_family_name, struct_split_name);
        let split_clone =
            self.generate_split_clone(generic_usage, generic_family_name, struct_split_name);
        let split_impl = self.generate_split_impl(
            generic_usage,
            generic_family_name,
            struct_split_name,
            struct_ref_name,
            struct_ref_mut_name,
        );
        let split_split =
            self.generate_split_split(generic_usage, generic_family_name, struct_split_name);
        let split_default =
            self.generate_split_default(generic_usage, generic_family_name, struct_split_name);

        quote! {
            #split
            #split_clone
            #split_impl
            #split_split
            #split_default
        }
    }

    fn generate_split(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let vis = &self.visibility;
        let generics_family = &generic_usage.generics_family;

        let fields = self.fields
                .iter()
                .map(|field| {
                    let name = &field.name;
                    let ty = &field.ty;
                    let ty = if field.nested {
                        quote! { <#ty as #crate_name::archetype::SplitFields<#generic_family_name>>::Split }
                    } else if let Some(ty) = &field.is_option {
                        quote! { #generic_family_name::SparseStorage<#ty> }
                    } else {
                        quote! { #generic_family_name::Storage<#ty> }
                    };
                    quote! {
                        pub #name: #ty,
                    }
                })
                .collect::<Vec<_>>();

        let struct_split_doc = format!(
            r#"Generated by `#[derive(SplitFields)]`.
This struct is a version of `{struct_name}` that holds each field in its own [Storage]({crate_name}::storage::Storage).

**Note**: It is not intended to be used directly, but rather as, for example, `SplitOf<Vec<{struct_name}>>`."#
        );

        quote! {
            #[doc = #struct_split_doc]
            #vis struct #struct_split_name<#generics_family> {
                #(#fields)*
            }
        }
    }

    fn generate_split_clone(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let generics_family = &generic_usage.generics_family;
        let generics_family_use = &generic_usage.generics_family_use;

        let constraints = self.fields
                .iter()
                .map(|field| {
                    let ty = &field.ty;
                    if field.nested {
                        quote! { <#ty as #crate_name::archetype::SplitFields<#generic_family_name>>::Split: Clone }
                    } else if let Some(ty) = &field.is_option {
                        quote! { #generic_family_name::SparseStorage<#ty>: Clone }
                    } else {
                        quote! { #generic_family_name::Storage<#ty>: Clone }
                    }
                })
                .collect::<Vec<_>>();

        let clone = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { #name: self.#name.clone(), }
            })
            .collect::<Vec<_>>();

        quote! {
                impl<#generics_family> Clone for #struct_split_name<#generics_family_use>
                where
                    #(#constraints),*
                {
                    fn clone(&self) -> Self {
                        Self {
                            #(#clone)*
                        }
                    }
                }
        }
    }

    fn generate_split_impl(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
        struct_ref_name: &syn::Ident,
        struct_ref_mut_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use,
            generics_family_use,
        } = generic_usage;

        let fields = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { #name, }
            })
            .collect::<Vec<_>>();

        let mut get = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                if field.is_option.is_some() {
                    quote! {
                        let #name = self.#name.get(id);
                    }
                } else {
                    quote! { let #name = self.#name.get(id)?; }
                }
            })
            .collect::<Vec<_>>();
        get.push(quote! {
            Some(#struct_ref_name {
                #(#fields)*
            })
        });

        let mut get_mut = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                if field.is_option.is_some() {
                    quote! {
                        let #name = self.#name.get_mut(id);
                    }
                } else {
                    quote! { let #name = self.#name.get_mut(id)?; }
                }
            })
            .collect::<Vec<_>>();
        get_mut.push(quote! {
            Some(#struct_ref_mut_name {
                #(#fields)*
            })
        });

        let mut get_unchecked = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                if field.is_option.is_some() {
                    quote! {
                        let #name = self.#name.get(id);
                    }
                } else {
                    quote! {
                        let #name = unsafe { self.#name.get_unchecked(id) };
                    }
                }
            })
            .collect::<Vec<_>>();
        get_unchecked.push(quote! {
            #struct_ref_name {
                #(#fields)*
            }
        });

        let mut get_unchecked_mut = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                if field.is_option.is_some() {
                    quote! {
                        let #name = self.#name.get_mut(id);
                    }
                } else {
                    quote! {
                        let #name = unsafe { self.#name.get_unchecked_mut(id) };
                    }
                }
            })
            .collect::<Vec<_>>();
        get_unchecked_mut.push(quote! {
            #struct_ref_mut_name {
                #(#fields)*
            }
        });

        let get_doc = format!(
            r#"Get an immutable reference to all components of this archetype, i.e. a [`{struct_ref_name}`]"#
        );
        let get_mut_doc = format!(
            r#"Get a mutable reference to all components of this archetype, i.e. a [`{struct_ref_mut_name}`]"#
        );

        let get_unchecked_doc = format!(
            r#"Get an immutable reference to all components of this archetype, i.e. a [`{struct_ref_name}`]

            # Safety
            The given `id` must be present in the storage.
            "#
        );
        let get_unchecked_mut_doc = format!(
            r#"Get a mutable reference to all components of this archetype, i.e. a [`{struct_ref_mut_name}`]

            # Safety
            The given `id` must be present in the storage.
            "#
        );

        quote! {
            impl<#generics_family> #struct_split_name<#generics_family_use> {
                pub fn new(&self) -> Self
                where
                    #struct_split_name<#generics_family_use>: ::std::default::Default
                {
                    Self::default()
                }

                #[doc = #get_doc]
                pub fn get(&self, id: #generic_family_name::Id) -> Option<#struct_ref_name<'_, #generics_use>> {
                    use #crate_name::storage::{Storage, SparseStorage};
                    #(#get)*
                }

                #[doc = #get_mut_doc]
                pub fn get_mut(&mut self, id: #generic_family_name::Id) -> Option<#struct_ref_mut_name<'_, #generics_use>> {
                    use #crate_name::storage::{Storage, SparseStorage};
                    #(#get_mut)*
                }

                #[doc = #get_unchecked_doc]
                pub unsafe fn get_unchecked(&self, id: #generic_family_name::Id) -> #struct_ref_name<'_, #generics_use> {
                    use #crate_name::storage::{Storage, SparseStorage};
                    #(#get_unchecked)*
                }

                #[doc = #get_unchecked_mut_doc]
                pub unsafe fn get_unchecked_mut(&mut self, id: #generic_family_name::Id) -> #struct_ref_mut_name<'_, #generics_use> {
                    use #crate_name::storage::{Storage, SparseStorage};
                    #(#get_unchecked_mut)*
                }
            }
        }
    }

    fn generate_split_split(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
    ) -> TokenStream {
        let crate_name = &self.crate_name;
        let struct_name = &self.name;
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use,
            generics_family_use,
        } = generic_usage;

        let insert = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                if field.is_option.is_some() {
                    quote! {
                        if let Some(field) = value.#name {
                            self.#name.insert(id, field);
                        }
                    }
                } else {
                    quote! {
                        self.#name.insert(id, value.#name);
                    }
                }
            })
            .collect::<Vec<_>>();

        let mut remove = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                if field.is_option.is_some() {
                    quote! {
                        let #name = self.#name.remove(id);
                    }
                } else {
                    quote! {
                        let #name = self.#name.remove(id)?;
                    }
                }
            })
            .collect::<Vec<_>>();
        let fields = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! {#name}
            })
            .collect::<Vec<_>>();
        remove.push(quote! { Some( #struct_name { #(#fields),* } )});

        quote! {
            impl<#generics_family> #crate_name::archetype::Split<#generic_family_name> for #struct_split_name<#generics_family_use> {
                type Item = #struct_name<#generics_use>;
                fn insert(&mut self, id: #generic_family_name::Id, value: Self::Item) {
                    use #crate_name::storage::{Storage, SparseStorage};
                    #(#insert)*
                }
                fn remove(&mut self, id: #generic_family_name::Id) -> Option<Self::Item> {
                    use #crate_name::storage::{Storage, SparseStorage};
                    #(#remove)*
                }
            }
        }
    }

    fn generate_split_default(
        &self,
        generic_usage: &GenericUsage,
        generic_family_name: &TokenStream,
        struct_split_name: &syn::Ident,
    ) -> TokenStream {
        let GenericUsage {
            generics: _,
            generics_family,
            generics_use: _,
            generics_family_use,
        } = generic_usage;

        let fields = self
            .fields
            .iter()
            .map(|field| {
                let name = &field.name;
                quote! { #name: ::std::default::Default::default(), }
            })
            .collect::<Vec<_>>();

        quote! {
            impl<#generics_family> ::std::default::Default for #struct_split_name<#generics_family_use>
            where
                #generic_family_name::IdGenerator: ::std::default::Default
            {
                fn default() -> Self {
                    Self {
                        #(#fields)*
                    }
                }
            }
        }
    }
}
