[package]
name = "stecs-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = []
query_mut = []

[dependencies]
darling = "0.20"
proc-macro2 = "1"
quote = "1"
thiserror = "1"
