name: Test
on:
  push:

jobs:
  test-native:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all-targets
      - name: Test documentation
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --doc
